
package com.agiliumlabs.smev.ws.impl.client.example;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.soap.MTOM;

import ru.gosuslugi.smev.rev120315.HeaderType;
import ru.gosuslugi.smev.rev120315.SyncRequestType;
import ru.gosuslugi.smev.rev120315.SyncResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MsgExamplePort", targetNamespace = "http://smev.gosuslugi.ru/MsgExample/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@MTOM(threshold=5*1024*1024)
public interface MsgExamplePort {


    /**
     * 
     * @param smevHeader
     * @param parameters
     * @return
     *     returns ru.gosuslugi.smev.msgexample.xsd.types.SyncResponseType
     */
    @WebMethod(action = "http://smev.gosuslugi.ru/MsgExample/syncReq")
    @WebResult(name = "SyncResponse", targetNamespace = "http://smev.gosuslugi.ru/MsgExample/xsd/types", partName = "parameters")
    public SyncResponseType syncReq(
        @WebParam(name = "Header", targetNamespace = "http://smev.gosuslugi.ru/rev120315", header = true, partName = "smevHeader")
        HeaderType smevHeader,
        @WebParam(name = "SyncRequest", targetNamespace = "http://smev.gosuslugi.ru/MsgExample/xsd/types", partName = "parameters")
        SyncRequestType parameters);

    /**
     * 
     * @param smevHeader
     * @param parameters
     * @return
     *     returns ru.gosuslugi.smev.msgexample.xsd.types.SyncResponseType
     */
    @WebMethod(action = "http://smev.gosuslugi.ru/MsgExample/aSyncReq")
    @WebResult(name = "aSyncReqResponse", targetNamespace = "http://smev.gosuslugi.ru/MsgExample/xsd/types", partName = "parameters")
    public SyncResponseType aSyncReq(
        @WebParam(name = "Header", targetNamespace = "http://smev.gosuslugi.ru/rev120315", header = true, partName = "smevHeader")
        HeaderType smevHeader,
        @WebParam(name = "aSyncReqRequest", targetNamespace = "http://smev.gosuslugi.ru/MsgExample/xsd/types", partName = "parameters")
        SyncRequestType parameters);

    /**
     * 
     * @param smevHeader
     * @param parameters
     * @return
     *     returns ru.gosuslugi.smev.msgexample.xsd.types.SyncResponseType
     */
    @WebMethod(action = "http://smev.gosuslugi.ru/MsgExample/aSyncResult")
    @WebResult(name = "aSyncResultResponse", targetNamespace = "http://smev.gosuslugi.ru/MsgExample/xsd/types", partName = "parameters")
    public SyncResponseType aSyncResult(
        @WebParam(name = "Header", targetNamespace = "http://smev.gosuslugi.ru/rev120315", header = true, partName = "smevHeader")
        HeaderType smevHeader,
        @WebParam(name = "aSyncResultRequest", targetNamespace = "http://smev.gosuslugi.ru/MsgExample/xsd/types", partName = "parameters")
        SyncRequestType parameters);

}
