
package com.agiliumlabs.smev.ws.impl.client.example;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "SmevServerService", targetNamespace = "http://smev.gosuslugi.ru/MsgExample/", wsdlLocation = "file:/Users/roman/Desktop/project/smev/smev.simple/src/wsdl/SID0003022.wsdl")
public class MsgExampleService
    extends Service
{

    private final static URL MSGEXAMPLESERVICE_WSDL_LOCATION;
    private final static WebServiceException MSGEXAMPLESERVICE_EXCEPTION;
    private final static QName MSGEXAMPLESERVICE_QNAME = new QName("http://smev.gosuslugi.ru/MsgExample/", "SmevServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/roman/Desktop/project/smev/smev.simple/src/wsdl/SID0003022.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MSGEXAMPLESERVICE_WSDL_LOCATION = url;
        MSGEXAMPLESERVICE_EXCEPTION = e;
    }

    public MsgExampleService() {
        super(__getWsdlLocation(), MSGEXAMPLESERVICE_QNAME);
    }

    public MsgExampleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MsgExamplePort
     */
    @WebEndpoint(name = "MsgExamplePort")
    public MsgExamplePort getMsgExamplePort() {
        return super.getPort(new QName("http://smev.gosuslugi.ru/MsgExample/", "MsgExamplePort"), MsgExamplePort.class);
    }

    private static URL __getWsdlLocation() {
        if (MSGEXAMPLESERVICE_EXCEPTION!= null) {
            throw MSGEXAMPLESERVICE_EXCEPTION;
        }
        return MSGEXAMPLESERVICE_WSDL_LOCATION;
    }

}
